# Generated by Django 5.2.5 on 2025-08-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_add',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
